"""AlphaMind Data Layer Schema — Target Entity Definitions.

This package defines the canonical schema for all data consumed by AlphaMind's
6-layer pipeline. Each module corresponds to a domain from the external data
specification (quantitative categories Q1-Q12, qualitative categories Qual 1-6).

Phase 1: Entity stubs (class + docstring, no fields) ✓ Complete
Phase 2: Field-level definitions with types, constraints, and documentation ✓ Complete

Entity naming convention:
    - Class names match the "Target Entity / Object" column in source-to-target-mapping.xlsx
    - Spec IDs (e.g., Q1:1a) are referenced in docstrings
    - Each entity maps 1:1 to a sub-category in the design spec

Package structure:
    Quantitative (10 modules, 64 entities):
        price_volume        Q1:1a-1g    7 entities
        order_flow          Q2:2a-2f    6 entities
        derivatives         Q3:3a-3h    8 entities
        short_selling       Q4:4a-4e    5 entities
        fundamentals        Q5:5a-5g    7 entities
        macro               Q6:6a-6f    6 entities
        cross_asset         Q7:7a-7g    7 entities
        commodities         Q8:8a-8f    6 entities
        volatility          Q11:11a-11f 6 entities
        corporate_actions   Q12:12a-12f 6 entities

    Qualitative (5 modules, 20 entities):
        news_sentiment      Qual 1:1a-1b + Qual 2:2a-2c   5 entities
        prediction_markets  Qual 3:3a-3c                   3 entities
        earnings_commentary Qual 4:4a-4e                   5 entities
        regulatory          Qual 5:5a-5d                   4 entities
        sector_catalysts    Qual 6:6a-6c                   3 entities

    Reference Data (1 module, 2 entities):
        reference           REF:UNIVERSE, REF:SECTOR       2 entities

    Unified (cross-cutting):
        events              Events:CAL — unified macro + policy event calendar   1 entity
        fundamentals        ValuationMultiples (Q5:VAL)                          1 entity

    Infrastructure:
        _common             Shared types, enums, and base definitions
        _registry           Spec ID → entity class mapping
"""

# Common types (imported by all domain modules)
from ._common import (
    AlphaMindSector,
    AnomalyFlag,
    DataConfidence,
    Direction,
    Exchange,
    HeadlineType,
    InflationRegime,
    InvocationMetadata,
    MarketCapBucket,
    MarketSession,
    SignalStrength,
    SourceCredibilityTier,
    Timeframe,
    TrendState,
    VolatilityRegime,
    YieldCurveRegime,
)

# Registry
from ._registry import ENTITY_REGISTRY

# Quantitative domains
from .commodities import (
    CommodityPositioning,
    CrackSpreads,
    CrudeOil,
    ETFFlowData,
    FuturesCurvePoint,
    IndustrialMetals,
    NaturalGas,
    PreciousMetals,
)
from .corporate_actions import (
    BuybackBlackout,
    BuybackProgram,
    ETFFlowImpact,
    EventType,
    IndexAddRemove,
    IndexName,
    IndexRebalance,
    InvestorEvent,
    InvestorEventCalendar,
    LockupSecondaryCalendar,
    LockupStatus,
    RegulatoryEvent,
    RegulatoryFiling,
    RegulatoryFilingType,
    SecondaryOffering,
)
from .cross_asset import (
    BreadthMetric,
    CorrelationPair,
    CorrelationRegimeChange,
    CrossSectorRotation,
    DivergenceEvent,
    ImpliedRealizedCorrelation,
    IndexConstituentBehavior,
    IntermarketRegimeFlag,
    IntermarketRegimeSignal,
    IntraSectorCorrelation,
    LeadLagRelationship,
    LeadLagTiming,
    SectorRotationSignal,
)
from .derivatives import (
    COTPositioning,
    CrossTickerOptionsSignal,
    CrossTickerPairSignal,
    DealerExposure,
    EarningsImpliedMove,
    EarningsImpliedMoveData,
    ExpirationCluster,
    GreekExposure,
    ImpliedVolSurface,
    IVTerm,
    OpenInterestLandscape,
    PCFlowBreakdown,
    PutCallDynamics,
    SectorETFFlowSnapshot,
    SectorETFOptionsFlow,
    StrikeOI,
    StrikeOIDistribution,
    SweepDetection,
    UnusualBlock,
    UnusualOptionsActivity,
    VolumeOIAnomaly,
)
from .earnings_commentary import (
    AnalystQADynamics,
    BellwetherRead,
    ConferencePresentation,
    CrossCompanyEarningsIntel,
    ForwardLookingStatement,
    ManagementToneAnalysis,
    NonAnswerFlag,
    QAExchange,
    QuestionTheme,
    SupplyChainSignal,
    TargetUpdate,
    TopicEmphasis,
)
from .events import (
    Event,
    EventCalendar,
    EventProximityFlag,
)
from .fundamentals import (
    AnalystRatingChange,
    AnalystRatings,
    AnalystTargetSnapshot,
    EarningsCalendar,
    EarningsEstimateDynamics,
    EarningsEstimates,
    EstimateRevision,
    InsiderInstitutionalOwnership,
    InsiderTransaction,
    MarginProfitabilityShift,
    RevenueGrowthTrajectory,
    ValuationMultiples,
)
from .macro import (
    BreakevenInflation,
    ConsumerData,
    CreditConditions,
    CurrencyAndDollar,
    CurrencyLevel,
    CurveSpread,
    DollarMoveAttribution,
    EmploymentData,
    FedPolicyExpectations,
    FedProbabilityAssessment,
    FundingMarketMetrics,
    FundingStressComposite,
    GrowthIndicators,
    HousingData,
    InflationDataRelease,
    InflationMetrics,
    PMISubcomponent,
    PrivateCreditMetrics,
    PublicCreditMetrics,
    RatePathExpectation,
    TreasuryAuctionResult,
    YieldCurve,
    YieldLevelAndChange,
)

# Qualitative domains
from .news_sentiment import (
    AlternativeSentimentProxy,
    BreakingHeadline,
    HeadlineCluster,
    KeyArgument,
    LongFormAnalysis,
    NewsVolume,
    OptionsFlowNarrative,
    PlatformSentimentBreakdown,
    SocialSentimentScore,
    UnusualOptionsActivityReport,
)
from .order_flow import (
    AuctionData,
    BlockTrade,
    ExtendedHoursFlow,
    FlowWindow,
    InstitutionalFlow,
    IntradayFlowPattern,
    LiquiditySnapshot,
    TimeOfDayAnomaly,
    TradeFlowAggregate,
    TradeSizeBreakdown,
    VenueVolume,
)
from .prediction_markets import (
    FOMCMeetingOdds,
    GeopoliticalContract,
    GeopoliticalOutcome,
    MonetaryPolicyOutcome,
    PolicyContract,
    RateProbabilityPair,
    RegulatoryPoliticalOutcome,
)
from .price_volume import (
    DivergenceFlag,
    ExtendedHoursBar,
    GapAnalysis,
    HistoricalContext,
    IndicatorReading,
    IntradayGap,
    MultiTimeframePriceBar,
    OHLCVBar,
    ReferenceLevels,
    RelativePerformance,
    SwingPoint,
    TechnicalIndicator,
    TimeframeTrend,
    VolumeProfile,
)

# Reference data
from .reference import (
    AssetUniverse,
    ETFMembership,
    ReclassificationEvent,
    SectorClassification,
    TickerChange,
)
from .regulatory import (
    ExecutiveAction,
    FedCommunication,
    GeopoliticalEvent,
    RegulatoryAction,
    StatementChange,
)
from .sector_catalysts import (
    CapexSignal,
    CompetitiveShift,
    EnergyCatalyst,
    FinancialsCatalyst,
    OPECStatement,
    ProductCycle,
    RegulatoryShift,
    TechSemiCatalyst,
)
from .short_selling import (
    BorrowCost,
    BorrowCostSnapshot,
    FeeTrendSnapshot,
    LendingMarketStructure,
    ShortInterestSnapshot,
    ShortVolumeDaily,
    ShortVolumeTrend,
    SqueezeComposite,
)
from .volatility import (
    VVIX,
    RealizedImpliedVolGap,
    SKEWIndex,
    SKEWTrend,
    VIXDynamics,
    VIXSKEWMatrix,
    VIXTermStructure,
    VIXTermStructureState,
    VIXVVIXMatrix,
    VolRegimeClassification,
)

__all__ = [
    "ENTITY_REGISTRY",
    "VVIX",
    "AlphaMindSector",
    "AlternativeSentimentProxy",
    "AnalystQADynamics",
    "AnalystRatingChange",
    "AnalystRatings",
    "AnalystTargetSnapshot",
    "AnomalyFlag",
    "AssetUniverse",
    "AuctionData",
    "BellwetherRead",
    "BlockTrade",
    "BorrowCost",
    "BorrowCostSnapshot",
    "BreadthMetric",
    "BreakevenInflation",
    "BreakingHeadline",
    "BuybackBlackout",
    "BuybackProgram",
    "COTPositioning",
    "CapexSignal",
    "CommodityPositioning",
    "CompetitiveShift",
    "ConferencePresentation",
    "ConsumerData",
    "CorrelationPair",
    "CorrelationRegimeChange",
    "CrackSpreads",
    "CreditConditions",
    "CrossCompanyEarningsIntel",
    "CrossSectorRotation",
    "CrossTickerOptionsSignal",
    "CrossTickerPairSignal",
    "CrudeOil",
    "CurrencyAndDollar",
    "CurrencyLevel",
    "CurveSpread",
    "DataConfidence",
    "DealerExposure",
    "Direction",
    "DivergenceEvent",
    "DivergenceFlag",
    "DollarMoveAttribution",
    "ETFFlowData",
    "ETFFlowImpact",
    "ETFMembership",
    "EarningsCalendar",
    "EarningsEstimateDynamics",
    "EarningsEstimates",
    "EarningsImpliedMove",
    "EarningsImpliedMoveData",
    "EmploymentData",
    "EnergyCatalyst",
    "EstimateRevision",
    "Event",
    "EventCalendar",
    "EventProximityFlag",
    "EventType",
    "Exchange",
    "ExecutiveAction",
    "ExpirationCluster",
    "ExtendedHoursBar",
    "ExtendedHoursFlow",
    "FOMCMeetingOdds",
    "FedCommunication",
    "FedPolicyExpectations",
    "FedProbabilityAssessment",
    "FeeTrendSnapshot",
    "FinancialsCatalyst",
    "FlowWindow",
    "ForwardLookingStatement",
    "FundingMarketMetrics",
    "FundingStressComposite",
    "FuturesCurvePoint",
    "GapAnalysis",
    "GeopoliticalContract",
    "GeopoliticalEvent",
    "GeopoliticalOutcome",
    "GreekExposure",
    "GrowthIndicators",
    "HeadlineCluster",
    "HeadlineType",
    "HistoricalContext",
    "HousingData",
    "IVTerm",
    "ImpliedRealizedCorrelation",
    "ImpliedVolSurface",
    "IndexAddRemove",
    "IndexConstituentBehavior",
    "IndexName",
    "IndexRebalance",
    "IndicatorReading",
    "IndustrialMetals",
    "InflationDataRelease",
    "InflationMetrics",
    "InflationRegime",
    "InsiderInstitutionalOwnership",
    "InsiderTransaction",
    "InstitutionalFlow",
    "IntermarketRegimeFlag",
    "IntermarketRegimeSignal",
    "IntraSectorCorrelation",
    "IntradayFlowPattern",
    "IntradayGap",
    "InvestorEvent",
    "InvestorEventCalendar",
    "InvocationMetadata",
    "KeyArgument",
    "LeadLagRelationship",
    "LeadLagTiming",
    "LendingMarketStructure",
    "LiquiditySnapshot",
    "LockupSecondaryCalendar",
    "LockupStatus",
    "LongFormAnalysis",
    "ManagementToneAnalysis",
    "MarginProfitabilityShift",
    "MarketCapBucket",
    "MarketSession",
    "MonetaryPolicyOutcome",
    "MultiTimeframePriceBar",
    "NaturalGas",
    "NewsVolume",
    "NonAnswerFlag",
    "OHLCVBar",
    "OPECStatement",
    "OpenInterestLandscape",
    "OptionsFlowNarrative",
    "PCFlowBreakdown",
    "PMISubcomponent",
    "PlatformSentimentBreakdown",
    "PolicyContract",
    "PreciousMetals",
    "PrivateCreditMetrics",
    "ProductCycle",
    "PublicCreditMetrics",
    "PutCallDynamics",
    "QAExchange",
    "QuestionTheme",
    "RatePathExpectation",
    "RateProbabilityPair",
    "RealizedImpliedVolGap",
    "ReclassificationEvent",
    "ReferenceLevels",
    "RegulatoryAction",
    "RegulatoryEvent",
    "RegulatoryFiling",
    "RegulatoryFilingType",
    "RegulatoryPoliticalOutcome",
    "RegulatoryShift",
    "RelativePerformance",
    "RevenueGrowthTrajectory",
    "SKEWIndex",
    "SKEWTrend",
    "SecondaryOffering",
    "SectorClassification",
    "SectorETFFlowSnapshot",
    "SectorETFOptionsFlow",
    "SectorRotationSignal",
    "ShortInterestSnapshot",
    "ShortVolumeDaily",
    "ShortVolumeTrend",
    "SignalStrength",
    "SocialSentimentScore",
    "SourceCredibilityTier",
    "SqueezeComposite",
    "StatementChange",
    "StrikeOI",
    "StrikeOIDistribution",
    "SupplyChainSignal",
    "SweepDetection",
    "SwingPoint",
    "TargetUpdate",
    "TechSemiCatalyst",
    "TechnicalIndicator",
    "TickerChange",
    "TimeOfDayAnomaly",
    "Timeframe",
    "TimeframeTrend",
    "TopicEmphasis",
    "TradeFlowAggregate",
    "TradeSizeBreakdown",
    "TreasuryAuctionResult",
    "TrendState",
    "UnusualBlock",
    "UnusualOptionsActivity",
    "UnusualOptionsActivityReport",
    "VIXDynamics",
    "VIXSKEWMatrix",
    "VIXTermStructure",
    "VIXTermStructureState",
    "VIXVVIXMatrix",
    "ValuationMultiples",
    "VenueVolume",
    "VolRegimeClassification",
    "VolatilityRegime",
    "VolumeOIAnomaly",
    "VolumeProfile",
    "YieldCurve",
    "YieldCurveRegime",
    "YieldLevelAndChange",
]
