"""Tier 2 — append-only lifecycle/event records per ``state-persistence.md``
§ Tier 2.

Event records capture state mutations and serve raw state category 5. Today
this subpackage hosts the activity log entry plus its per-event-type detail
payloads; fill records and other Tier 2 entities are tracked separately and
will be reorganized here in follow-up work.
"""

from __future__ import annotations

from alphamind.portfolio_state.events.activity_log import (
    EVENT_TYPE_TO_DETAIL_CLASS,
    EVENT_TYPE_TO_GROUP,
    ActivityLogEntry,
    AnyDetailType,
    BracketActivatedDetail,
    BracketCancelledCorporateActionDetail,
    BracketCompletedDetail,
    BracketDissolvedDetail,
    BracketIncompleteWarningDetail,
    BracketModificationSource,
    BracketModifiedDetail,
    CapitalReleasedDetail,
    CapitalReservedDetail,
    CashCreditedDetail,
    CashCreditReason,
    CashDebitedDetail,
    CashDebitReason,
    CommandAbandonedDetail,
    CorporateActionAppliedDetail,
    CorporateActionType,
    DistillationConfigChange,
    DistillationConfigChangeDetail,
    EnvelopeParseFailedDetail,
    EnvelopeRejectionDetail,
    EventGroup,
    EventSource,
    EventType,
    GuardrailRejectionDetail,
    MarginCallDetail,
    MarginCallResolvedDetail,
    MarginLiquidationDetail,
    OrderCancelledDetail,
    OrderExpiredDetail,
    OrderFilledDetail,
    OrderModifiedDetail,
    OrderPartiallyFilledDetail,
    OrderRejectedDetail,
    OrderRejectionSource,
    OrderSubmittedDetail,
    PMDecisionDetail,
    PMVerdict,
    PositionAddedDetail,
    PositionClosedDetail,
    PositionExitMethod,
    PositionOpenedDetail,
    PositionOpenMechanism,
    PositionReducedDetail,
    RiskLimitApproachedDetail,
    RiskParameterChangedDetail,
    ThesisComponentAddedDetail,
    ThesisComponentUpdatedDetail,
    ThesisCreatedDetail,
    ThesisResolvedDetail,
    ThesisStatusChangedDetail,
)

__all__ = [
    "EVENT_TYPE_TO_DETAIL_CLASS",
    "EVENT_TYPE_TO_GROUP",
    "ActivityLogEntry",
    "AnyDetailType",
    "BracketActivatedDetail",
    "BracketCancelledCorporateActionDetail",
    "BracketCompletedDetail",
    "BracketDissolvedDetail",
    "BracketIncompleteWarningDetail",
    "BracketModificationSource",
    "BracketModifiedDetail",
    "CapitalReleasedDetail",
    "CapitalReservedDetail",
    "CashCreditReason",
    "CashCreditedDetail",
    "CashDebitReason",
    "CashDebitedDetail",
    "CommandAbandonedDetail",
    "CorporateActionAppliedDetail",
    "CorporateActionType",
    "DistillationConfigChange",
    "DistillationConfigChangeDetail",
    "EnvelopeParseFailedDetail",
    "EnvelopeRejectionDetail",
    "EventGroup",
    "EventSource",
    "EventType",
    "GuardrailRejectionDetail",
    "MarginCallDetail",
    "MarginCallResolvedDetail",
    "MarginLiquidationDetail",
    "OrderCancelledDetail",
    "OrderExpiredDetail",
    "OrderFilledDetail",
    "OrderModifiedDetail",
    "OrderPartiallyFilledDetail",
    "OrderRejectedDetail",
    "OrderRejectionSource",
    "OrderSubmittedDetail",
    "PMDecisionDetail",
    "PMVerdict",
    "PositionAddedDetail",
    "PositionClosedDetail",
    "PositionExitMethod",
    "PositionOpenMechanism",
    "PositionOpenedDetail",
    "PositionReducedDetail",
    "RiskLimitApproachedDetail",
    "RiskParameterChangedDetail",
    "ThesisComponentAddedDetail",
    "ThesisComponentUpdatedDetail",
    "ThesisCreatedDetail",
    "ThesisResolvedDetail",
    "ThesisStatusChangedDetail",
]
