"""Smoke import test: every public name from models package resolves (story 02)."""

import alphamind.config.models as models_mod

_EXPECTED_PUBLIC_NAMES = {
    "AdaptiveAgentConfig",
    "AgentName",
    "AgentsConfig",
    "AgentsSection",
    "AllowedModel",
    "Alpaca",
    "AlpacaCredentials",
    "AnalystMode",
    "AnalystOutputMode",
    "AnomalyDetection",
    "AntiPatternSpike",
    "AssetRole",
    "AssetsConfig",
    "BackoffStrategy",
    "BaseAgentConfig",
    "Benchmark",
    "BreachResponse",
    "CategoryConfig",
    "CitationChainShift",
    "CollectorEntry",
    "CollectorScheduleConfig",
    "CommandType",
    "CredibilityTier",
    "CriticalityTier",
    "CrossReferenceError",
    "DataSourcesConfig",
    "DigestConfig",
    "DiscoverySource",
    "DiscoveryVendor",
    "DistillationConfig",
    "EmergencyInvocation",
    "EnforcementTier",
    "EscalationZones",
    "EventType",
    "ExecutionConfig",
    "ExecutionMode",
    "FailureMode",
    "FeatureFlags",
    "FinalInvocationBeforeEvent",
    "GreeksRefresh",
    "GuardrailsConfig",
    "LLMFailureConfig",
    "LeadLag",
    "LoadedConfig",
    "LoosenOnExit",
    "MainConfig",
    "Mode",
    "ModeConfig",
    "NarrativeLag",
    "NewsDigestConfig",
    "NewsOutletsConfig",
    "OrderType",
    "OutletEntry",
    "Overlay",
    "PaperHarness",
    "Paths",
    "PendingOrdersDefault",
    "PersistenceWindows",
    "PmEmphasis",
    "PmMode",
    "PreEventActivation",
    "PreEventOverlay",
    "PredictionMarket",
    "Profile",
    "ProfileConfig",
    "ProgressiveTier",
    "ProviderConfig",
    "QualitativeResearcherSection",
    "REGISTERED_TOOLS",
    "Regime",
    "RegimeChange",
    "RegimeClassification",
    "RegimeConfig",
    "RegimeTransition",
    "ResolvedConfig",
    "RetryCondition",
    "RetryPolicy",
    "RetryShapeConfig",
    "RetryStrategy",
    "RiskPriority",
    "RuleEntry",
    "RunType",
    "RunTypeConfig",
    "RuntimeDimensions",
    "SchedulerConfig",
    "SectorUnderperform",
    "SemanticInvariantError",
    "SessionHours",
    "SessionWindow",
    "SnapshotResult",
    "SourceSignalSurvivalDrop",
    "StrategistAction",
    "StrategistMode",
    "StrategistOutputMode",
    "StressActivation",
    "StressOverlay",
    "StressTrigger",
    "ThesisPerformanceReviewConfig",
    "TightenOnEntry",
    "TokenBudgetRange",
    "TransitionPolicy",
    "ValidationSuperseded",
    "ValidationWindowEnd",
    "VenueConfig",
    "compose_config",
    "enumerate_compositions",
    "persist_snapshot",
    "validate_cross_references",
    "validate_semantic_invariants",
}


def test_all_public_names_importable() -> None:
    for name in _EXPECTED_PUBLIC_NAMES:
        assert hasattr(models_mod, name), f"{name!r} not importable from alphamind.config.models"


def test_all_exports_in_dunder_all() -> None:
    assert set(models_mod.__all__) == _EXPECTED_PUBLIC_NAMES


def test_models_is_package() -> None:
    assert hasattr(models_mod, "__path__"), "models must be a package, not a module"


def test_env_example_keys_in_package_namespace() -> None:
    assert hasattr(models_mod, "_ENV_EXAMPLE_KEYS"), (
        "_ENV_EXAMPLE_KEYS must be in the package namespace for monkeypatch"
    )
