"""Integration tests for the debug-e2e seeder against an alembic-migrated DB.

The companion unit tests in ``test_seed.py`` use ``Base.metadata.create_all``
and assert on row counts at the SQL layer; they do NOT exercise the
downstream snapshot-assembly path. This file fills that gap — a fresh DB
goes through the production alembic chain, then :func:`wipe_and_seed`
populates it from :data:`SYNTHETIC_PORTFOLIO`, then assertions confirm
the seeded state satisfies the read-side invariants that the orchestrator
hits during ``_assemble_phase1_snapshot``.

These tests are the canonical regression net for the debug-e2e seeder's
"fully-fresh DB" workflow. Each invariant maps to a verification-run
failure mode we observed on a fresh Windows DB (Mac-vs-fresh divergence;
the Mac DB had accumulated state across runs that masked seeder gaps).
"""

from __future__ import annotations

from argparse import Namespace
from collections.abc import AsyncIterator
from datetime import UTC, datetime
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from alphamind.persistence.session import (
    make_async_engine,
    make_async_session_factory,
)
from alphamind.portfolio_state.computations.positions import (
    compute_strategy_market_value_usd,
)
from alphamind.portfolio_state.pricing import PriceQuote, PriceSource
from alphamind.portfolio_state.records.positions import StrategyPositionDetails
from alphamind.scheduler.debug_e2e.portfolio import SYNTHETIC_PORTFOLIO
from alphamind.scheduler.debug_e2e.seed import wipe_and_seed
from alphamind.state.tables import (
    DrawdownStateRow,
    PositionRow,
    ThesisComponentRow,
    ThesisRow,
)
from alphamind.state.tables.drawdown_state import DRAWDOWN_STATE_SINGLETON_ID
from alphamind.state.tables.positions_codec import row_to_record
from alphamind.state.tables.theses_codec import rows_to_record

_NOW = datetime(2026, 5, 17, 14, 30, tzinfo=UTC)


def _leg_quote(price_usd: float) -> PriceQuote:
    """A fresh leg-price quote — mirrors the snapshot assembler's MTM fallback."""
    return PriceQuote(
        ticker="UNUSED",
        price_usd=price_usd,
        as_of_timestamp=_NOW,
        source=PriceSource.INTRADAY_QUOTE,
        is_stale=False,
    )


def _alembic_config(db_path: Path) -> Config:
    repo_root = Path(__file__).parents[3]
    return Config(
        repo_root / "alembic.ini",
        cmd_opts=Namespace(x=[f"db={db_path}"]),
    )


@pytest.fixture()
async def migrated_factory(
    tmp_path: Path,
) -> AsyncIterator[tuple[Path, async_sessionmaker[AsyncSession]]]:
    """Yield ``(db_path, async_session_factory)`` over a fresh alembic-migrated DB.

    The DB filename ends in ``-debug-e2e.db`` so :func:`wipe_and_seed`'s
    suffix guard accepts it. Migrations apply via the production alembic
    chain (not ``Base.metadata.create_all``) so any DDL difference between
    autogenerated metadata and the migration history surfaces here.
    """
    db_path = tmp_path / "alphamind-debug-e2e.db"
    command.upgrade(_alembic_config(db_path), "head")

    async_engine = make_async_engine(str(db_path))
    factory = make_async_session_factory(async_engine)
    try:
        yield db_path, factory
    finally:
        await async_engine.dispose()


async def _run_seed(
    factory: async_sessionmaker[AsyncSession],
    db_path: Path,
) -> None:
    async with factory() as session:
        await wipe_and_seed(
            session=session,
            now=_NOW,
            db_path=str(db_path),
            portfolio=SYNTHETIC_PORTFOLIO,
        )


class TestSeederPostStateInvariants:
    """Each test pins one invariant the snapshot assembler relies on.

    A failure here predicts a corresponding ``--debug-e2e`` subprocess
    failure on a fully-fresh DB; a pass guards against regression of an
    already-fixed gap.
    """

    async def test_drawdown_state_singleton_is_seeded(
        self,
        migrated_factory: tuple[Path, async_sessionmaker[AsyncSession]],
    ) -> None:
        """``SqlPortfolioStateRepository.get_drawdown_state`` raises on missing row.

        Until the seeder explicitly populated the singleton, the snapshot
        assembler crashed during step 2 of :func:`assemble_snapshot` with
        ``RepositoryConsistencyError: drawdown_state singleton row is
        missing — run Phase 1 to seed it``. Phase 1 cannot seed it because
        the snapshot assembly runs BEFORE Phase 1's write paths.
        """
        db_path, factory = migrated_factory
        await _run_seed(factory, db_path)

        async with factory() as session:
            row = await session.get(DrawdownStateRow, DRAWDOWN_STATE_SINGLETON_ID)

        assert row is not None
        assert row.equity_high_water_mark_usd == float(SYNTHETIC_PORTFOLIO.starting_cash_usd)
        assert row.current_drawdown_pct == 0.0

    async def test_active_theses_round_trip_through_codec(
        self,
        migrated_factory: tuple[Path, async_sessionmaker[AsyncSession]],
    ) -> None:
        """``rows_to_record`` validates ACTIVE theses against the record invariants.

        ``ThesisRecord.__post_init__`` requires:
        - ``components`` non-empty for ACTIVE status,
        - components covering ``ENTRY_RATIONALE`` / ``TARGET_RATIONALE`` /
          ``INVALIDATION_RATIONALE``,
        - ``resolution_*`` fields are ``None`` for ACTIVE.

        Reconstructing each seeded thesis exercises the same codec the
        repository's ``_read_theses_by_status`` uses; a raise here predicts
        the snapshot assembler's ``get_active_theses`` call will explode.
        """
        db_path, factory = migrated_factory
        await _run_seed(factory, db_path)

        async with factory() as session:
            thesis_rows = (await session.execute(select(ThesisRow))).scalars().all()
            component_rows = (await session.execute(select(ThesisComponentRow))).scalars().all()

        assert len(thesis_rows) == len(SYNTHETIC_PORTFOLIO.theses)
        components_by_thesis: dict[str, list[ThesisComponentRow]] = {}
        for component_row in component_rows:
            components_by_thesis.setdefault(component_row.thesis_id, []).append(component_row)

        for thesis_row in thesis_rows:
            children = tuple(components_by_thesis.get(thesis_row.thesis_id, ()))
            # Construction will raise ValueError on any of the post-init invariants.
            record = rows_to_record(thesis_row, children)
            assert record.status.value == "ACTIVE"
            assert len(record.components) == 3
            assert {c.component_type.value for c in record.components} == {
                "ENTRY_RATIONALE",
                "TARGET_RATIONALE",
                "INVALIDATION_RATIONALE",
            }

    async def test_strategy_position_leg_premiums_are_positive(
        self,
        migrated_factory: tuple[Path, async_sessionmaker[AsyncSession]],
    ) -> None:
        """Strategy legs need ``premium_paid_per_contract > 0``.

        The pricing layer's ``PriceQuote.__post_init__`` rejects
        ``price_usd <= 0`` (``ValueError: price_usd must be > 0; got 0.0``).
        The seeder's ``_build_strategy_position_row`` used to hardcode 0.0
        per leg because :class:`SyntheticStrategyLeg` carries no per-leg
        premium; that hardcoded value reached the pricing layer via
        ``_price_fields_strategy`` and crashed snapshot assembly.
        """
        import json

        db_path, factory = migrated_factory
        await _run_seed(factory, db_path)

        async with factory() as session:
            strategy_rows = (
                (
                    await session.execute(
                        select(PositionRow).where(PositionRow.instrument_type == "STRATEGY")
                    )
                )
                .scalars()
                .all()
            )

        assert strategy_rows, "synthetic portfolio must include at least one strategy position"
        for row in strategy_rows:
            details = json.loads(row.details_json)
            for leg in details["legs"]:
                premium = leg["options"]["premium_paid_per_contract"]
                assert premium > 0.0, (
                    f"strategy {row.position_id} leg {leg['leg_id']} has "
                    f"premium_paid_per_contract={premium}; pricing layer rejects price_usd<=0"
                )

    async def test_strategy_position_marks_to_cost_basis_at_seed_time(
        self,
        migrated_factory: tuple[Path, async_sessionmaker[AsyncSession]],
    ) -> None:
        """A freshly-seeded strategy position marks to its cost basis (≈ $0 P/L).

        Every synthetic position is a "just placed" entry, so its P/L should
        read ≈ $0 — as the seeded equity and option positions do. The seeder
        picks each strategy leg's ``premium_paid_per_contract`` (the snapshot
        assembler's mark-to-market fallback, since debug-e2e seeds no
        option-price snapshots) so the direction-aware leg sum equals
        ``net_premium_usd``. An even split across legs nets a debit spread to
        ≈ $0 market value against a non-zero cost basis — a -100% P/L artifact
        on debug-pos-07; see ALP-582.
        """
        db_path, factory = migrated_factory
        await _run_seed(factory, db_path)

        async with factory() as session:
            strategy_rows = (
                (
                    await session.execute(
                        select(PositionRow).where(PositionRow.instrument_type == "STRATEGY")
                    )
                )
                .scalars()
                .all()
            )

        assert strategy_rows, "synthetic portfolio must include at least one strategy position"
        for row in strategy_rows:
            record = row_to_record(row)
            assert isinstance(record.details, StrategyPositionDetails)
            # No option-price snapshot is seeded, so each leg marks to its
            # entry premium — the same fallback the snapshot assembler uses.
            leg_prices = {
                leg.leg_id: _leg_quote(leg.options.premium_paid_per_contract)
                for leg in record.details.legs
            }
            market_value = compute_strategy_market_value_usd(record, leg_prices)
            cost_basis = record.details.net_premium_usd
            assert market_value == pytest.approx(cost_basis)
            # A strategy's P/L USD is the directionless ``market_value -
            # net_premium_usd`` — the assembler computes it this way, not via
            # the direction-keyed ``compute_unrealized_pnl_usd`` (a strategy
            # carries ``direction = None``).
            pnl = market_value - cost_basis
            assert pnl == pytest.approx(0.0)


_PROD_SNAPSHOT_PATH = Path("data/alphamind-debug-e2e.db")


def _expected_portfolio_tickers() -> set[str]:
    tickers: set[str] = set()
    for position in SYNTHETIC_PORTFOLIO.positions:
        ticker = getattr(position, "symbol", None) or getattr(position, "underlying", None)
        assert ticker is not None
        tickers.add(str(ticker))
    return tickers


def _prepare_snapshot_copy(tmp_path: Path) -> Path:
    """Copy the local prod snapshot into ``tmp_path``; skip the test if absent.

    Pulled out of the async fixture body because ASYNC240 forbids
    synchronous ``Path.exists()`` / ``shutil.copy2`` inside an async
    coroutine; the I/O is intentionally sync (one-shot setup), so a
    sync helper is the right shape rather than wrapping in
    ``asyncio.to_thread``.
    """
    import shutil

    if not _PROD_SNAPSHOT_PATH.exists():
        pytest.skip(
            f"snapshot at {_PROD_SNAPSHOT_PATH!s} absent; run "
            "scripts/snapshot_prod_for_debug_e2e.py to populate it"
        )

    db_path = tmp_path / "alphamind-debug-e2e.db"
    shutil.copy2(_PROD_SNAPSHOT_PATH, db_path)
    return db_path


@pytest.fixture()
async def snapshot_factory(
    tmp_path: Path,
) -> AsyncIterator[tuple[Path, async_sessionmaker[AsyncSession]]]:
    """Yield ``(db_path, async_session_factory)`` over a copy of the prod snapshot.

    The snapshot at :data:`_PROD_SNAPSHOT_PATH` is produced by
    ``scripts/snapshot_prod_for_debug_e2e.py`` — a file copy of the
    production DB onto a debug-e2e target. It carries the full data layer
    (``asset_universe``, ``sector_classification``, distillation
    baselines, news clusters, event calendar, ...) the orchestrator's
    pre-SDK phases consume; ``wipe_and_seed`` overlays the synthetic
    portfolio on top.

    Skips if the local snapshot is absent so the suite remains runnable
    on machines (CI, fresh dev boxes) that haven't run the snapshot
    script.
    """
    db_path = _prepare_snapshot_copy(tmp_path)
    async_engine = make_async_engine(str(db_path))
    factory = make_async_session_factory(async_engine)
    try:
        yield db_path, factory
    finally:
        await async_engine.dispose()


class TestSeederAgainstProdSnapshot:
    """The post-wipe-and-seed snapshot must satisfy the orchestrator's pre-SDK FKs.

    The snapshot-from-prod approach (alternative to expanding the seeder's
    scope into the data layer) lets ``wipe_and_seed`` continue to own
    state-persistence wipe + synthetic portfolio seed while the data
    layer comes from the production-faithful snapshot. These tests pin
    the load-bearing invariants the orchestrator's Phase-1 prep / snapshot
    assembly / distillation bootstrap rely on, without running any SDK
    calls.
    """

    async def test_portfolio_tickers_present_in_asset_universe(
        self,
        snapshot_factory: tuple[Path, async_sessionmaker[AsyncSession]],
    ) -> None:
        """asset_universe is the FK target for distillation_ticker_baseline.

        The orchestrator's distillation bootstrap inserts a zero-baseline
        row on first sight of each portfolio ticker; that INSERT fails
        with ``FOREIGN KEY constraint failed`` unless every ticker
        already has an ``asset_universe`` row. The snapshot provides them;
        ``wipe_and_seed`` must not delete them.
        """
        from alphamind.persistence.models import AssetUniverse

        db_path, factory = snapshot_factory
        await _run_seed(factory, db_path)

        async with factory() as session:
            present = set((await session.execute(select(AssetUniverse.ticker))).scalars().all())

        missing = _expected_portfolio_tickers() - present
        assert not missing, f"asset_universe missing tickers after wipe_and_seed: {missing!s}"

    async def test_distillation_ticker_baseline_bootstrap_insert_succeeds(
        self,
        snapshot_factory: tuple[Path, async_sessionmaker[AsyncSession]],
    ) -> None:
        """Reproduce the exact INSERT the orchestrator's bootstrap path runs.

        On a fresh Windows DB without a prod snapshot this INSERT raised
        ``sqlite3.IntegrityError: FOREIGN KEY constraint failed`` because
        ``asset_universe`` was empty. With the snapshot in place, the
        same INSERT must succeed for any portfolio ticker — confirming
        the orchestrator can advance past distillation prep into the
        SDK-bound layers.
        """
        from sqlalchemy import text

        db_path, factory = snapshot_factory
        await _run_seed(factory, db_path)

        # Pick the same statement the orchestrator runs on first ticker sight;
        # the column list mirrors the actual failing SQL captured during
        # the fresh-Windows verify attempts.
        async with factory() as session:
            # Delete any pre-existing baseline rows for the smoke-test
            # ticker so the INSERT is idempotent across reruns.
            await session.execute(
                text(
                    "DELETE FROM distillation_ticker_baseline "
                    "WHERE ticker = :t AND baseline_kind = :k"
                ),
                {"t": "AAPL", "k": "volume"},
            )
            await session.execute(
                text(
                    "INSERT INTO distillation_ticker_baseline "
                    "(ticker, baseline_kind, as_of, mean, stdev, n_observations, "
                    " window_days, calibration_state, ingested_at) "
                    "VALUES (:t, :k, :as_of, 0.0, 0.0, 0, 20, 'bootstrap', :ing)"
                ),
                {
                    "t": "AAPL",
                    "k": "volume",
                    "as_of": "2026-05-17T06:52:08Z",
                    "ing": "2026-05-17T06:52:08Z",
                },
            )
            await session.commit()
