"""Breach-behavior package: zones, forced reduction, halt mode, cascades, emergencies.

Public surface: configuration knobs, canonical typed value objects, and (in
later stories) the primitives that compose them. Re-exports below give every
downstream consumer a single import path.
"""

from alphamind.risk_guardrails.breach_behavior.config import (
    BreachBehaviorConfig,
    load_breach_behavior_config,
)
from alphamind.risk_guardrails.breach_behavior.hard_rejection import (
    LibraryOutputProtocol,
    RuleProjectionProtocol,
    compose_hard_rejection_payload,
)
from alphamind.risk_guardrails.breach_behavior.types import (
    ActiveRiskParameterSet,
    BreachDetails,
    BreachResponse,
    CloseRationaleType,
    Direction,
    DrawdownState,
    DrawdownTier,
    EmergencyContext,
    EmergencyTrigger,
    EnforcementTier,
    EngineCloseCommand,
    EngineEnvelope,
    EngineGuardrailTriggerRecord,
    EscalationZones,
    HaltState,
    HardRejectionPayload,
    InstrumentType,
    PositionRecord,
    PositionSelectionAction,
    PositionSelectionResult,
    ProgressiveTier,
    RegimeLabel,
    RegimeTransitionState,
    RejectionRuleEntry,
    RiskBudgetConsumption,
    RiskBudgetEntry,
    RiskManagementSubtype,
    RiskZone,
    SecondaryBreachCheckResult,
    SecondaryBreachOutcome,
)

__all__ = [
    "ActiveRiskParameterSet",
    "BreachBehaviorConfig",
    "BreachDetails",
    "BreachResponse",
    "CloseRationaleType",
    "Direction",
    "DrawdownState",
    "DrawdownTier",
    "EmergencyContext",
    "EmergencyTrigger",
    "EnforcementTier",
    "EngineCloseCommand",
    "EngineEnvelope",
    "EngineGuardrailTriggerRecord",
    "EscalationZones",
    "HaltState",
    "HardRejectionPayload",
    "InstrumentType",
    "LibraryOutputProtocol",
    "PositionRecord",
    "PositionSelectionAction",
    "PositionSelectionResult",
    "ProgressiveTier",
    "RegimeLabel",
    "RegimeTransitionState",
    "RejectionRuleEntry",
    "RiskBudgetConsumption",
    "RiskBudgetEntry",
    "RiskManagementSubtype",
    "RiskZone",
    "RuleProjectionProtocol",
    "SecondaryBreachCheckResult",
    "SecondaryBreachOutcome",
    "compose_hard_rejection_payload",
    "load_breach_behavior_config",
]
