"""Generate the per-package module-navigation tables in nested CLAUDE.md files.

For each ``CLAUDE.md`` under ``src/alphamind/`` that contains the ``BEGIN``/``END``
markers, this lists the package's immediate children (subpackages + top-level modules)
with each child's *docstring first line*, rendered as a markdown table between the
markers. The descriptions are therefore sourced from the code itself — to change a row,
edit that module's docstring, not this table.

    uv run python scripts/gen_package_nav.py            # rewrite tables in place
    uv run python scripts/gen_package_nav.py --check    # exit 1 if any table is stale

The ``--check`` mode backs ``tests/docs/test_package_nav_fresh.py`` so a stale table
fails CI. Add the marker pair to a package's CLAUDE.md to opt it into a table.
"""

from __future__ import annotations

import argparse
import ast
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC = REPO_ROOT / "src" / "alphamind"

BEGIN = (
    "<!-- BEGIN modules (generated by scripts/gen_package_nav.py"
    " — edit docstrings, not this block) -->"
)
END = "<!-- END modules -->"


def _doc_first_line(py: Path) -> str:
    try:
        doc = ast.get_docstring(ast.parse(py.read_text(encoding="utf-8")), clean=True)
    except (SyntaxError, OSError):
        return ""
    if not doc:
        return ""
    return doc.strip().splitlines()[0].strip()


# Trailing tracking refs and RST roles are navigation noise — strip them for the table.
_TICKET_PAREN = re.compile(r"\s*\((?:story\s+)?[^)]*\bALP-\d+[^)]*\)\.?\s*$")
_STORY_CLAUSE = re.compile(r"\s*[—-]\s*stor(?:y|ies)\b.*$", re.IGNORECASE)
_RST_ROLE = re.compile(r":[a-z]+:`")


def _summary(py: Path) -> str:
    text = _doc_first_line(py)
    text = _RST_ROLE.sub("`", text).replace("``", "`")
    prev = ""
    while prev != text:
        prev = text
        text = _TICKET_PAREN.sub("", text)
        text = _STORY_CLAUSE.sub("", text)
    text = text.strip().replace("|", r"\|")
    return text or "—"


def _children(pkg: Path) -> list[tuple[str, Path]]:
    """Immediate subpackages (name + their __init__.py) and top-level modules."""
    out: list[tuple[str, Path]] = []
    for child in sorted(pkg.iterdir(), key=lambda p: p.name):
        if child.name in {"__init__.py", "__pycache__"}:
            continue
        if child.is_dir() and (child / "__init__.py").exists():
            out.append((child.name + "/", child / "__init__.py"))
        elif child.suffix == ".py":
            out.append((child.name, child))
    return out


def render_block(pkg: Path) -> str:
    rows = [f"| `{name}` | {_summary(src)} |" for name, src in _children(pkg)]
    if not rows:
        return "_(no submodules)_"
    return "| Module | Responsibility |\n|---|---|\n" + "\n".join(rows)


def marked_files() -> list[Path]:
    return sorted(
        p for p in SRC.rglob("CLAUDE.md") if BEGIN in p.read_text(encoding="utf-8")
    )


def apply(path: Path, *, write: bool) -> bool:
    """Rewrite the marker block in ``path``. Returns True if content changed."""
    text = path.read_text(encoding="utf-8")
    pre, rest = text.split(BEGIN, 1)
    _, post = rest.split(END, 1)
    new = f"{pre}{BEGIN}\n{render_block(path.parent)}\n{END}{post}"
    if new != text and write:
        path.write_text(new, encoding="utf-8")
    return new != text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if any table is stale")
    args = parser.parse_args(argv)

    stale = [p for p in marked_files() if apply(p, write=not args.check)]
    if args.check and stale:
        print("Stale module tables — run: uv run python scripts/gen_package_nav.py")
        for p in stale:
            print(f"  {p.relative_to(REPO_ROOT)}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
